baseURL = "http://opstecwang.github.io/"
languageCode = "zh-CN"
title = "opstecwang"
theme = "maupassant"

[author]
  name = "opstecwang"


[params]
  author = "opstecwang"
  subtitle = "Python、shell、DevOps、SRE"
  keywords = "golang,go语言,go语言笔记,飞雪无情,java,android,博客,项目管理,python,软件架构,公众号,小程序"
  description = "专注于IT互联网，包括但不限于Go语言(golang)、Java、Android、Python、项目管理、抖音分析、软件架构等"
  beian = "沪ICP备20020475号"
  busuanzi = true #启用不算子网页统计
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录


## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单
[menu]
  [[menu.main]]
    identifier = "books"
    name = "读书"
    url = "/books/"
    weight = 2

  [[menu.main]]
    identifier = "parenting"
    name = "育儿"
    url = "/parenting/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

## 友情链接，可以多个
[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"



## 配置 utteranc评论,教程参考 https://utteranc.es/
#[params.utteranc]
#  enable = true
#  repo = "your github repo" ##换成自己得
#  issueTerm = "pathname"
#  theme = "github-light"


## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 70

disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启




### 配置 utteranc评论,教程参考 https://utteranc.es/
#[params.utteranc]
#  enable = true
#  repo = "your github repo" ##换成自己得
#  issueTerm = "pathname"
#  theme = "github-light"
#
### 开启版权声明，协议名字和链接都可以换
#[params.cc]
#    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
#    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"











